source 'https://cdn.cocoapods.org/'

project "MBoxCore.xcodeproj"
platform :osx, '10.15'

inhibit_all_warnings!
use_frameworks!

target 'MBoxCore' do
  podspec :subspec => 'Core'
  pod 'CocoaLumberjack/Swift', :git=>'git@github.com:Whirlwind/CocoaLumberjack.git', :branch=>'mbox2'
end

target 'MBoxCoreTests' do
  pod 'Nimble'
end
